from __future__ import annotations

from datetime import datetime
from typing import Optional

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    ARRAY,
    JSON,
)
from sqlalchemy.orm import declarative_base, relationship


Base = declarative_base()


class Submission(Base):
    __tablename__ = "submissions"

    id = Column(String(36), primary_key=True, index=True)  # UUID 문자열
    user_id = Column(Integer, nullable=True, index=True)
    subject = Column(String(100), nullable=False, index=True)
    total_score = Column(Float, nullable=False)
    max_score = Column(Integer, nullable=False)
    time_taken = Column(Integer, nullable=True)
    summary = Column(Text, nullable=True)
    recommendations_json = Column(Text, nullable=True)
    submitted_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    items = relationship("SubmissionItem", back_populates="submission", cascade="all, delete-orphan")


class SubmissionItem(Base):
    __tablename__ = "submission_items"

    id = Column(Integer, primary_key=True, index=True)
    submission_id = Column(String(36), ForeignKey("submissions.id", ondelete="CASCADE"), nullable=False, index=True)
    question_id = Column(Integer, nullable=False)
    user_answer = Column(Text, nullable=False)
    skipped = Column(Boolean, default=False, nullable=False)
    score = Column(Float, nullable=False)
    correct_answer = Column(String(200), nullable=False)
    topic = Column(String(100), nullable=False, index=True)

    submission = relationship("Submission", back_populates="items")


class Feedback(Base):
    __tablename__ = "feedbacks"

    id = Column(Integer, primary_key=True, index=True)
    submission_item_id = Column(Integer, ForeignKey("submission_items.id", ondelete="CASCADE"), nullable=False, index=True)
    feedback_text = Column(Text, nullable=False)
    ai_generated = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class Question(Base):
    __tablename__ = "questions"

    id = Column(Integer, primary_key=True, index=True)
    subject = Column(String(100), nullable=False, index=True)
    topic = Column(String(100), nullable=False, index=True)
    
    # 계층적 구조 지원
    subject_path = Column(String(500), nullable=True, index=True)  # "/saas_dev/backend/python/variables"
    
    question_type = Column(String(50), nullable=False)
    code_snippet = Column(Text, nullable=False)
    correct_answer = Column(String(200), nullable=False)
    difficulty = Column(String(20), nullable=False)
    taxonomy_level = Column(String(50), nullable=True, default="application")  # 추가된 필드
    hint = Column(Text, nullable=True)  # 추가된 필드
    explanation = Column(Text, nullable=True)  # 추가된 필드
    rubric = Column(Text, nullable=True)
    created_by = Column(String(100), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)

    # New columns for AI question support
    question_data = Column(JSON, nullable=True)  # Additional question data (JSONB in Postgres)
    question_metadata = Column(JSON, nullable=True)  # Metadata like hints, explanations (JSONB in Postgres)
    ai_generated = Column(Boolean, default=False, nullable=False)  # Whether generated by AI
    
    # Explicitly define the index with the existing name
    __table_args__ = (
        Index('idx_question_ai_generated', 'ai_generated'),
        Index('idx_question_subject_path', 'subject_path'),
    )


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String(255), nullable=False, unique=True, index=True)
    password_hash = Column(String(255), nullable=False)
    password_salt = Column(String(64), nullable=False)
    role = Column(String(20), nullable=False, default="student", index=True)
    display_name = Column(String(100), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    last_login_at = Column(DateTime, nullable=True)
    # Relationships (bring in session/activity models from older schema)
    quiz_sessions = relationship("QuizSession", back_populates="user")
    recent_activities = relationship("RecentActivity", back_populates="user")
    # MVP: 구독 관계
    subscriptions = relationship("Subscription", back_populates="user")


class RefreshToken(Base):
    __tablename__ = "refresh_tokens"

    id = Column(String(64), primary_key=True, index=True)  # token id
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    issued_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    expires_at = Column(DateTime, nullable=False)
    revoked = Column(Boolean, default=False, nullable=False)

class Subject(Base):
    __tablename__ = "subjects"

    id = Column(Integer, primary_key=True, index=True)
    key = Column(String(100), nullable=False, unique=True, index=True)
    title = Column(String(200), nullable=False)
    version = Column(String(50), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    # Phase 8 추가 컬럼들
    description = Column(Text, nullable=True)
    category = Column(String(50), nullable=True, default='programming_fundamentals')
    difficulty_level = Column(String(20), nullable=True, default='beginner')
    estimated_duration = Column(String(50), nullable=True)
    icon_name = Column(String(50), nullable=True)
    color_code = Column(String(10), nullable=True)
    is_active = Column(Boolean, nullable=True, default=True)
    order_index = Column(Integer, nullable=True, default=0)
    total_problems = Column(Integer, nullable=True, default=0)
    total_students = Column(Integer, nullable=True, default=0)
    average_completion_rate = Column(Float, nullable=True, default=0.0)
    updated_at = Column(DateTime, nullable=True, default=datetime.utcnow)


class Topic(Base):
    __tablename__ = "topics"

    id = Column(Integer, primary_key=True, index=True)
    key = Column(String(100), nullable=False, unique=True, index=True)
    title = Column(String(200), nullable=False)
    parent_topic_id = Column(Integer, ForeignKey("topics.id"), nullable=True)


class QuizSession(Base):
    """퀴즈 세션 - database.py와 중복되므로 orm.py의 정의를 우선 사용"""
    __tablename__ = "quiz_sessions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    session_type = Column(String(50), default="python_basics")
    total_questions = Column(Integer)
    answered_questions = Column(Integer)
    skipped_questions = Column(Integer)
    total_score = Column(Float)
    time_taken = Column(Integer)
    completed_at = Column(DateTime, default=datetime.utcnow)

    # quiz settings
    shuffle_enabled = Column(Boolean, default=True)
    easy_count = Column(Integer, default=4)
    medium_count = Column(Integer, default=4)
    hard_count = Column(Integer, default=2)

    # relationships
    user = relationship("User", back_populates="quiz_sessions")
    answers = relationship("QuizAnswer", back_populates="session", cascade="all, delete-orphan")


class QuizAnswer(Base):
    """퀴즈 답변 - database.py와 중복되므로 orm.py의 정의를 우선 사용"""
    __tablename__ = "quiz_answers"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(Integer, ForeignKey("quiz_sessions.id", ondelete="CASCADE"), nullable=False, index=True)
    question_id = Column(Integer)
    user_answer = Column(Text)
    correct_answer = Column(String(200))
    is_correct = Column(Boolean)
    is_skipped = Column(Boolean, default=False)
    score = Column(Float, default=0.0)
    answered_at = Column(DateTime, default=datetime.utcnow)

    # relationship
    session = relationship("QuizSession", back_populates="answers")


class RecentActivity(Base):
    """최근 활동 - database.py와 중복되므로 orm.py의 정의를 우선 사용"""
    __tablename__ = "recent_activities"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    activity_type = Column(String(50))
    activity_description = Column(String(200))
    score = Column(Float, nullable=True)
    topic = Column(String(100), nullable=True)
    difficulty = Column(String(20), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    # relationship
    user = relationship("User", back_populates="recent_activities")


class SubjectTopic(Base):
    __tablename__ = "subject_topics"

    id = Column(Integer, primary_key=True, index=True)
    subject_key = Column(String(100), ForeignKey("subjects.key", ondelete="CASCADE"), nullable=False, index=True)
    topic_key = Column(String(100), ForeignKey("topics.key", ondelete="CASCADE"), nullable=False, index=True)
    weight = Column(Float, default=1.0, nullable=False)
    is_core = Column(Boolean, default=True, nullable=False)
    display_order = Column(Integer, default=0, nullable=False)
    show_in_coverage = Column(Boolean, default=True, nullable=False)
    # Phase 8 추가 컬럼들
    topic_name = Column(String(200), nullable=True)
    description = Column(Text, nullable=True)
    order_index = Column(Integer, nullable=True)
    estimated_duration = Column(String(50), nullable=True)
    difficulty_level = Column(String(20), nullable=True)


class SubjectSettings(Base):
    __tablename__ = "subject_settings"

    id = Column(Integer, primary_key=True, index=True)
    subject_key = Column(String(100), ForeignKey("subjects.key", ondelete="CASCADE"), nullable=False, unique=True, index=True)
    min_attempts = Column(Integer, default=3, nullable=False)
    min_accuracy = Column(Float, default=0.6, nullable=False)


class Group(Base):
    __tablename__ = "groups"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(200), nullable=False, unique=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class GroupMember(Base):
    __tablename__ = "group_members"

    id = Column(Integer, primary_key=True, index=True)
    group_id = Column(Integer, ForeignKey("groups.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)


class TeacherGroup(Base):
    __tablename__ = "teacher_groups"

    id = Column(Integer, primary_key=True, index=True)
    group_id = Column(Integer, ForeignKey("groups.id", ondelete="CASCADE"), nullable=False, index=True)
    teacher_user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)


class StudentAssignment(Base):
    __tablename__ = "student_assignments"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    subject = Column(String(100), nullable=False, index=True)
    topic_key = Column(String(100), nullable=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


# Phase 1: 확장 가능한 커리큘럼 아키텍처 모델들

class CurriculumCategory(Base):
    """커리큘럼 카테고리 (최상위 레벨)"""
    __tablename__ = "curriculum_categories"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False, unique=True, index=True)  # 'saas_development'
    display_name = Column(String(100), nullable=False)  # 'SaaS 개발자 종합과정'
    description = Column(Text, nullable=True)
    target_audience = Column(String(100), nullable=True)  # 'beginner_to_professional'
    estimated_total_months = Column(Integer, default=12)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # 관계 설정
    tracks = relationship("LearningTrack", back_populates="curriculum_category")


class LearningTrack(Base):
    """학습 트랙 (중간 레벨) - 새로 생성"""
    __tablename__ = "learning_tracks"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False, unique=True, index=True)  # 'python_basics'
    display_name = Column(String(100), nullable=False)  # 'Python 기초'
    category = Column(String(50), nullable=False)  # 'foundation', 'development', 'specialization'
    curriculum_category_id = Column(Integer, ForeignKey("curriculum_categories.id"), nullable=True)
    specialization_level = Column(String(50), default='general')  # 'general', 'specialist', 'expert', 'master'
    prerequisite_tracks = Column(ARRAY(Text), default=[])  # 선수 트랙들
    difficulty_level = Column(Integer, default=1)  # 1-5
    estimated_hours = Column(Integer, default=20)
    description = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # 관계 설정
    curriculum_category = relationship("CurriculumCategory", back_populates="tracks")
    modules = relationship("LearningModule", back_populates="track")


class LearningModule(Base):
    """학습 모듈 (최하위 레벨)"""
    __tablename__ = "learning_modules"
    
    id = Column(Integer, primary_key=True, index=True)
    track_id = Column(Integer, ForeignKey("learning_tracks.id"), nullable=False)
    name = Column(String(100), nullable=False)  # 'react_hooks'
    display_name = Column(String(100), nullable=False)  # 'React Hooks 마스터'
    module_type = Column(String(50), default='core')  # 'core', 'elective', 'project', 'certification'
    estimated_hours = Column(Integer, default=8)
    difficulty_level = Column(Integer, default=1)  # 1-5
    prerequisites = Column(ARRAY(Text), default=[])  # 다른 모듈 이름들
    tags = Column(ARRAY(Text), default=[])  # ['frontend', 'state-management', 'hooks']
    industry_focus = Column(String(100), default='general')  # 'fintech', 'ecommerce', 'enterprise'
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # 관계 설정
    track = relationship("LearningTrack", back_populates="modules")
    resources = relationship("LearningResource", back_populates="module")


class LearningResource(Base):
    """AI 참고자료 시스템"""
    __tablename__ = "learning_resources"
    
    id = Column(Integer, primary_key=True, index=True)
    module_id = Column(Integer, ForeignKey("learning_modules.id"), nullable=True)
    track_id = Column(Integer, ForeignKey("learning_tracks.id"), nullable=False)
    sub_topic = Column(String(100), nullable=True)
    resource_type = Column(String(50), nullable=False)  # 'documentation', 'tutorial', 'video', 'project'
    title = Column(String(200), nullable=False)
    url = Column(Text, nullable=False)
    description = Column(Text, nullable=True)
    difficulty_level = Column(Integer, default=1)
    industry_focus = Column(String(100), default='general')
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # 관계 설정
    module = relationship("LearningModule", back_populates="resources")


# Phase 2: 개인화 엔진을 위한 모델들

class UserProgress(Base):
    """사용자 학습 진도 추적"""
    __tablename__ = "user_progress"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    track_id = Column(Integer, ForeignKey("learning_tracks.id"), nullable=False, index=True)
    module_id = Column(Integer, ForeignKey("learning_modules.id"), nullable=True, index=True)
    
    # 진도 상태
    status = Column(String(50), default='not_started', nullable=False)  # 'not_started', 'in_progress', 'completed', 'paused'
    completion_percentage = Column(Float, default=0.0, nullable=False)  # 0.0 ~ 100.0
    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)
    last_accessed_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # 학습 데이터
    total_attempts = Column(Integer, default=0, nullable=False)
    successful_attempts = Column(Integer, default=0, nullable=False)
    time_spent_minutes = Column(Integer, default=0, nullable=False)
    
    # 메타데이터
    current_difficulty = Column(Integer, default=1, nullable=False)  # 적응형 난이도
    learning_velocity = Column(Float, default=1.0, nullable=False)  # 학습 속도 계수
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # 관계 설정
    user = relationship("User")
    track = relationship("LearningTrack")
    module = relationship("LearningModule")


class UserWeakness(Base):
    """사용자 약점/강점 분석"""
    __tablename__ = "user_weaknesses"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # 약점 분류
    category = Column(String(100), nullable=False, index=True)  # 'concept', 'syntax', 'logic', 'debugging'
    subcategory = Column(String(100), nullable=True)  # 'loops', 'functions', 'data_structures'
    topic = Column(String(100), nullable=False)  # 구체적 주제
    
    # 약점 데이터
    error_count = Column(Integer, default=1, nullable=False)
    accuracy_rate = Column(Float, default=0.0, nullable=False)  # 0.0 ~ 1.0
    avg_time_taken = Column(Float, default=0.0, nullable=False)  # 평균 소요 시간(초)
    
    # AI 분석 결과
    weakness_type = Column(String(50), nullable=False)  # 'critical', 'moderate', 'minor'
    suggested_practice = Column(Text, nullable=True)  # AI 추천 연습 방법
    improvement_trend = Column(String(20), default='stable', nullable=False)  # 'improving', 'stable', 'declining'
    
    # 메타데이터
    first_detected_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    last_updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    is_resolved = Column(Boolean, default=False, nullable=False)
    resolved_at = Column(DateTime, nullable=True)
    
    # 관계 설정
    user = relationship("User")


class UserTrackProgress(Base):
    """사용자별 트랙 진행 상황"""
    __tablename__ = "user_track_progress"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    track_id = Column(Integer, ForeignKey("learning_tracks.id"), nullable=False, index=True)
    
    # 트랙 상태
    status = Column(String(50), default='not_started', nullable=False)
    enrollment_date = Column(DateTime, default=datetime.utcnow, nullable=False)
    estimated_completion_date = Column(DateTime, nullable=True)
    actual_completion_date = Column(DateTime, nullable=True)
    
    # 진도 메트릭
    modules_completed = Column(Integer, default=0, nullable=False)
    total_modules = Column(Integer, default=0, nullable=False)
    overall_accuracy = Column(Float, default=0.0, nullable=False)
    total_time_spent = Column(Integer, default=0, nullable=False)  # 분 단위
    
    # 개인화 데이터
    preferred_difficulty = Column(Integer, default=2, nullable=False)  # 1-5
    learning_pace = Column(String(20), default='normal', nullable=False)  # 'slow', 'normal', 'fast'
    industry_preference = Column(String(100), default='general', nullable=False)
    
    # 추천 시스템 데이터
    next_recommended_module_id = Column(Integer, ForeignKey("learning_modules.id"), nullable=True)
    recommendation_reason = Column(Text, nullable=True)
    last_recommendation_at = Column(DateTime, nullable=True)
    
    # 메타데이터
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # 관계 설정
    user = relationship("User")
    track = relationship("LearningTrack")
    next_recommended_module = relationship("LearningModule", foreign_keys=[next_recommended_module_id])


class LearningGoal(Base):
    """사용자 학습 목표"""
    __tablename__ = "learning_goals"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # 목표 설정
    title = Column(String(200), nullable=False)
    description = Column(Text, nullable=True)
    target_completion_date = Column(DateTime, nullable=True)
    priority_level = Column(Integer, default=3, nullable=False)  # 1(낮음) ~ 5(높음)
    
    # 목표 분류
    goal_type = Column(String(50), nullable=False)  # 'skill_mastery', 'project_completion', 'career_milestone'
    target_tracks = Column(ARRAY(Integer), default=[], nullable=False)  # 관련 트랙 ID들
    success_criteria = Column(Text, nullable=True)  # 성공 기준
    
    # 진행 상황
    status = Column(String(50), default='active', nullable=False)  # 'active', 'completed', 'paused', 'cancelled'
    progress_percentage = Column(Float, default=0.0, nullable=False)
    milestones_achieved = Column(ARRAY(Text), default=[], nullable=False)
    
    # 메타데이터
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    completed_at = Column(DateTime, nullable=True)
    
    # 관계 설정
    user = relationship("User")


class PersonalizedRecommendation(Base):
    """개인화된 추천 기록"""
    __tablename__ = "personalized_recommendations"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # 추천 내용
    recommendation_type = Column(String(50), nullable=False)  # 'next_module', 'skill_reinforcement', 'career_path'
    recommended_item_type = Column(String(50), nullable=False)  # 'module', 'track', 'resource', 'project'
    recommended_item_id = Column(Integer, nullable=False)
    
    # 추천 이유
    reasoning = Column(Text, nullable=False)
    confidence_score = Column(Float, default=0.5, nullable=False)  # 0.0 ~ 1.0
    algorithm_version = Column(String(50), default='v1.0', nullable=False)
    
    # 사용자 반응
    user_action = Column(String(50), nullable=True)  # 'accepted', 'declined', 'ignored', 'postponed'
    feedback_rating = Column(Integer, nullable=True)  # 1-5 별점
    user_feedback = Column(Text, nullable=True)
    
    # 결과 추적
    was_helpful = Column(Boolean, nullable=True)
    completion_rate = Column(Float, nullable=True)  # 추천 항목 완료율
    time_to_complete = Column(Integer, nullable=True)  # 완료까지 소요 시간(분)
    
    # 메타데이터
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    actioned_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)
    
    # 관계 설정
    user = relationship("User")


# Phase 2: 실무 프로젝트 연계 모델들

class ProjectTemplate(Base):
    """실무 프로젝트 템플릿"""
    __tablename__ = "project_templates"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(200), nullable=False, unique=True, index=True)
    display_name = Column(String(200), nullable=False)
    description = Column(Text, nullable=False)
    
    # 프로젝트 분류
    project_type = Column(String(50), nullable=False)  # 'web_app', 'api', 'data_analysis', 'mobile_app'
    difficulty_level = Column(Integer, default=2, nullable=False)  # 1-5
    estimated_hours = Column(Integer, default=20, nullable=False)
    
    # 기술 스택
    required_skills = Column(ARRAY(Text), default=[], nullable=False)  # 필수 기술
    technologies = Column(ARRAY(Text), default=[], nullable=False)    # 사용 기술
    industry_focus = Column(String(100), default='general', nullable=False)
    
    # 프로젝트 구조
    project_structure = Column(Text, nullable=True)  # JSON 형태의 프로젝트 구조
    starter_code = Column(Text, nullable=True)       # 시작 코드
    requirements_file = Column(Text, nullable=True)  # requirements.txt 내용
    
    # 평가 기준
    evaluation_criteria = Column(Text, nullable=False)  # 평가 기준
    success_metrics = Column(ARRAY(Text), default=[], nullable=False)
    
    # 메타데이터
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # 관계 설정
    user_projects = relationship("UserProject", back_populates="template")


class UserProject(Base):
    """사용자 프로젝트 진행 상황"""
    __tablename__ = "user_projects"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    template_id = Column(Integer, ForeignKey("project_templates.id"), nullable=False, index=True)
    
    # 프로젝트 상태
    status = Column(String(50), default='not_started', nullable=False)  # 'not_started', 'in_progress', 'completed', 'paused'
    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)
    deadline = Column(DateTime, nullable=True)
    
    # 진행 정보
    progress_percentage = Column(Float, default=0.0, nullable=False)
    current_milestone = Column(String(100), nullable=True)
    completed_milestones = Column(ARRAY(Text), default=[], nullable=False)
    
    # 프로젝트 파일
    project_repository = Column(String(500), nullable=True)  # GitHub 등 저장소 URL
    deployed_url = Column(String(500), nullable=True)        # 배포된 프로젝트 URL
    submission_files = Column(Text, nullable=True)           # 제출 파일 정보 (JSON)
    
    # 평가 결과
    self_evaluation_score = Column(Float, nullable=True)     # 자기 평가 점수
    peer_evaluation_score = Column(Float, nullable=True)     # 동료 평가 점수
    instructor_evaluation_score = Column(Float, nullable=True)  # 강사 평가 점수
    final_score = Column(Float, nullable=True)
    
    # 피드백
    instructor_feedback = Column(Text, nullable=True)
    improvement_suggestions = Column(Text, nullable=True)
    
    # 메타데이터
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # 관계 설정
    user = relationship("User")
    template = relationship("ProjectTemplate", back_populates="user_projects")


class Portfolio(Base):
    """사용자 포트폴리오"""
    __tablename__ = "portfolios"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True, index=True)
    
    # 기본 정보
    title = Column(String(200), nullable=False)
    bio = Column(Text, nullable=True)
    profile_image_url = Column(String(500), nullable=True)
    
    # 기술 스택
    skills = Column(ARRAY(Text), default=[], nullable=False)
    specializations = Column(ARRAY(Text), default=[], nullable=False)
    
    # 연락처
    email = Column(String(100), nullable=True)
    github_url = Column(String(500), nullable=True)
    linkedin_url = Column(String(500), nullable=True)
    website_url = Column(String(500), nullable=True)
    
    # 포트폴리오 설정
    is_public = Column(Boolean, default=False, nullable=False)
    custom_domain = Column(String(100), nullable=True, unique=True)
    theme = Column(String(50), default='modern', nullable=False)
    
    # 통계
    view_count = Column(Integer, default=0, nullable=False)
    last_viewed_at = Column(DateTime, nullable=True)
    
    # 메타데이터
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # 관계 설정
    user = relationship("User")
    project_showcases = relationship("PortfolioProject", back_populates="portfolio")


class PortfolioProject(Base):
    """포트폴리오에 표시할 프로젝트"""
    __tablename__ = "portfolio_projects"
    
    id = Column(Integer, primary_key=True, index=True)
    portfolio_id = Column(Integer, ForeignKey("portfolios.id", ondelete="CASCADE"), nullable=False, index=True)
    user_project_id = Column(Integer, ForeignKey("user_projects.id"), nullable=True)  # 연계된 학습 프로젝트
    
    # 프로젝트 정보
    title = Column(String(200), nullable=False)
    description = Column(Text, nullable=False)
    technologies = Column(ARRAY(Text), default=[], nullable=False)
    
    # 링크
    demo_url = Column(String(500), nullable=True)
    repository_url = Column(String(500), nullable=True)
    
    # 이미지/미디어
    thumbnail_url = Column(String(500), nullable=True)
    screenshots = Column(ARRAY(Text), default=[], nullable=False)
    
    # 메타데이터
    display_order = Column(Integer, default=0, nullable=False)
    is_featured = Column(Boolean, default=False, nullable=False)
    completion_date = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # 관계 설정
    portfolio = relationship("Portfolio", back_populates="project_showcases")
    user_project = relationship("UserProject")


# Phase 8 추가 모델들

class SubjectCategory(Base):
    """과목 카테고리 테이블 (scripts에서 생성됨)"""
    __tablename__ = "subject_categories"
    
    id = Column(Integer, primary_key=True, index=True)
    key = Column(String(50), unique=True, nullable=False, index=True)
    name = Column(String(100), nullable=False)
    description = Column(Text, nullable=True)
    color_code = Column(String(10), nullable=True)
    order_index = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)


class SubjectHierarchy(Base):
    """계층적 과목 구조 - 무한 확장 가능"""
    __tablename__ = "subject_hierarchy"
    
    id = Column(Integer, primary_key=True, index=True)
    key = Column(String(100), nullable=False, unique=True, index=True)
    title = Column(String(200), nullable=False)
    
    # 계층 구조
    parent_id = Column(Integer, ForeignKey("subject_hierarchy.id"), nullable=True, index=True)
    level = Column(Integer, nullable=False, default=0, index=True)  # 0:카테고리, 1:영역, 2:과목, 3:토픽
    path = Column(String(500), nullable=False, unique=True, index=True)  # "/saas_dev/backend/python/variables"
    
    # 메타데이터
    description = Column(Text, nullable=True)
    difficulty_level = Column(String(20), default='beginner')
    estimated_duration = Column(String(50), nullable=True)
    
    # UI 정보
    icon_name = Column(String(50), nullable=True)
    color_code = Column(String(10), nullable=True)
    order_index = Column(Integer, default=0)
    
    # 상태
    is_active = Column(Boolean, default=True, nullable=False)
    is_core = Column(Boolean, default=True, nullable=False)  # 핵심/선택 여부
    
    # 통계 (자동 계산)
    total_problems = Column(Integer, default=0)
    total_students = Column(Integer, default=0)
    average_completion_rate = Column(Float, default=0.0)
    
    # 학습 경로 정보
    prerequisites = Column(ARRAY(String), default=list)  # 선수 과목/토픽 키들
    learning_objectives = Column(JSON, default=list)
    
    # 생성/수정 시간
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # 관계
    parent = relationship("SubjectHierarchy", remote_side=[id], back_populates="children")
    children = relationship("SubjectHierarchy", back_populates="parent", cascade="all, delete-orphan")
    
    # 인덱스
    __table_args__ = (
        Index('idx_subject_hierarchy_path', 'path'),
        Index('idx_subject_hierarchy_level', 'level'),
        Index('idx_subject_hierarchy_parent_id', 'parent_id'),
        Index('idx_subject_hierarchy_active', 'is_active'),
    )


# ============================================================
# MVP: 결제 및 구독 시스템
# ============================================================

class Subscription(Base):
    """
    사용자 구독 정보
    
    비즈니스 규칙:
    - 한 사용자는 하나의 활성 구독만 가능
    - 체험(trial) → 유료(active) 자동 전환
    - 취소 시 current_period_end까지 유지
    """
    __tablename__ = "subscriptions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True, index=True)
    
    # 구독 상태
    status = Column(String(20), nullable=False, default="trial", index=True)  # trial, active, cancelled, expired
    plan = Column(String(20), nullable=False, default="monthly")  # monthly, annual
    
    # 체험 기간
    trial_start_date = Column(DateTime, nullable=True)
    trial_end_date = Column(DateTime, nullable=True)
    
    # 결제 기간
    current_period_start = Column(DateTime, nullable=True)
    current_period_end = Column(DateTime, nullable=True)
    
    # 취소 관련
    cancel_at_period_end = Column(Boolean, default=False, nullable=False)
    cancelled_at = Column(DateTime, nullable=True)
    
    # 타임스탬프
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    user = relationship("User", back_populates="subscriptions")
    payments = relationship("Payment", back_populates="subscription", cascade="all, delete-orphan")
    
    # 인덱스
    __table_args__ = (
        Index('idx_subscription_user_status', 'user_id', 'status'),
        Index('idx_subscription_period_end', 'current_period_end'),
    )


class Payment(Base):
    """
    결제 트랜잭션 기록
    
    비즈니스 규칙:
    - 구독과 1:N 관계 (갱신마다 새 결제)
    - 실패한 결제도 기록 (재시도 추적)
    - order_id는 unique (멱등성 보장)
    """
    __tablename__ = "payments"

    id = Column(Integer, primary_key=True, index=True)
    subscription_id = Column(Integer, ForeignKey("subscriptions.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # 토스페이먼츠 정보
    payment_key = Column(String(255), nullable=True, unique=True, index=True)  # 토스 결제 키
    order_id = Column(String(255), nullable=False, unique=True, index=True)  # 주문 ID (멱등성)
    
    # 결제 정보
    amount = Column(Integer, nullable=False)  # 결제 금액 (원)
    status = Column(String(20), nullable=False, default="pending", index=True)  # pending, success, failed, refunded
    payment_method = Column(String(50), nullable=True)  # card, bank, etc
    
    # 결제 결과
    paid_at = Column(DateTime, nullable=True)
    failed_reason = Column(Text, nullable=True)
    
    # 환불 정보
    refunded_at = Column(DateTime, nullable=True)
    refund_reason = Column(Text, nullable=True)
    refund_amount = Column(Integer, nullable=True)
    
    # 타임스탬프
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    subscription = relationship("Subscription", back_populates="payments")
    
    # 인덱스
    __table_args__ = (
        Index('idx_payment_subscription_status', 'subscription_id', 'status'),
        Index('idx_payment_created_at', 'created_at'),
    )


class Quote(Base):
    """
    명언 시스템
    
    166개 명언을 DB로 관리하여:
    - 동적 수정 가능
    - 카테고리별 필터링
    - 랜덤 선택 최적화
    """
    __tablename__ = "quotes"

    id = Column(Integer, primary_key=True, index=True)
    
    # 내용
    content = Column(Text, nullable=False)
    author = Column(String(100), nullable=True)
    source = Column(String(200), nullable=True)
    
    # 분류
    category = Column(String(50), nullable=True, index=True)  # "courage", "failure", "success", "persistence", etc.
    
    # 메타데이터
    order_number = Column(Integer, nullable=False, unique=True, index=True)  # 1-166 (원본 순서)
    is_active = Column(Boolean, default=True, nullable=False, index=True)
    
    # 타임스탬프
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # 인덱스
    __table_args__ = (
        Index('idx_quote_category_active', 'category', 'is_active'),
        Index('idx_quote_active_order', 'is_active', 'order_number'),
    )


class UserNote(Base):
    """
    사용자 메모 시스템
    
    학습 중 작성하는 메모를 관리:
    - 커리큘럼별 메모
    - 섹션별 메모 (교재/실습/퀴즈)
    - 검색 및 필터링
    """
    __tablename__ = "user_notes"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # 연결된 학습 콘텐츠
    track_id = Column(Integer, ForeignKey("learning_tracks.id"), nullable=True, index=True)
    module_id = Column(Integer, ForeignKey("learning_modules.id"), nullable=True, index=True)
    section = Column(String(50), nullable=True)  # "textbook", "practice", "quiz", "general"
    
    # 메모 내용
    title = Column(String(200), nullable=True)  # 메모 제목 (선택적)
    content = Column(Text, nullable=False)
    
    # 태그 및 분류
    tags = Column(ARRAY(String), default=list, nullable=False)  # ["python", "loops", "debugging"]
    is_important = Column(Boolean, default=False, nullable=False)  # 중요 메모 표시
    
    # 타임스탬프
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # 관계 설정
    user = relationship("User")
    track = relationship("LearningTrack")
    module = relationship("LearningModule")
    
    # 인덱스
    __table_args__ = (
        Index('idx_user_note_user_created', 'user_id', 'created_at'),
        Index('idx_user_note_track', 'track_id'),
        Index('idx_user_note_module', 'module_id'),
        Index('idx_user_note_important', 'is_important'),
    )


# ============================================================
# Phase C: 감성적 기능 (Emotional Support)
# ============================================================

class LearningContext(Base):
    """
    학습 컨텍스트 추적
    
    학습자의 현재 상태, 감정, 환경을 기록하여
    개인화된 지원 제공
    """
    __tablename__ = "learning_contexts"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # 학습 세션 정보
    session_id = Column(String(100), nullable=True, index=True)  # 세션 구분용
    track_id = Column(Integer, ForeignKey("learning_tracks.id"), nullable=True)
    module_id = Column(Integer, ForeignKey("learning_modules.id"), nullable=True)
    
    # 감정 상태 (기분 체크인)
    mood = Column(String(20), nullable=True)  # "great", "good", "okay", "struggling", "frustrated"
    energy_level = Column(Integer, nullable=True)  # 1-10 (1: 매우 피곤, 10: 매우 활기참)
    confidence_level = Column(Integer, nullable=True)  # 1-10 (1: 자신 없음, 10: 매우 자신 있음)
    
    # 학습 환경
    study_duration_minutes = Column(Integer, nullable=True)  # 계획한 학습 시간
    actual_duration_minutes = Column(Integer, nullable=True)  # 실제 학습 시간
    is_first_session_today = Column(Boolean, default=True)
    interruptions_count = Column(Integer, default=0)  # 중단 횟수
    
    # 학습 패턴
    time_of_day = Column(String(20), nullable=True)  # "morning", "afternoon", "evening", "night"
    is_consecutive_day = Column(Boolean, default=False)  # 연속 학습 중인가
    consecutive_days_count = Column(Integer, default=0)  # 연속 학습 일수
    
    # 학습 목표 및 동기
    daily_goal = Column(String(200), nullable=True)  # 오늘의 학습 목표
    motivation_level = Column(Integer, nullable=True)  # 1-10 동기부여 수준
    why_learning_today = Column(Text, nullable=True)  # 오늘 왜 학습하는가
    
    # 어려움 및 지원
    current_struggle = Column(Text, nullable=True)  # 현재 겪고 있는 어려움
    needs_encouragement = Column(Boolean, default=False)  # 격려가 필요한가
    preferred_support_type = Column(String(50), nullable=True)  # "gentle", "motivational", "technical"
    
    # 메타데이터
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # 관계 설정
    user = relationship("User")
    track = relationship("LearningTrack")
    module = relationship("LearningModule")
    
    # 인덱스
    __table_args__ = (
        Index('idx_learning_context_user_created', 'user_id', 'created_at'),
        Index('idx_learning_context_session', 'session_id'),
        Index('idx_learning_context_mood', 'mood'),
    )


class MoodCheckIn(Base):
    """
    기분 체크인 기록
    
    학습 전후의 감정 상태를 추적하여
    학습이 감정에 미치는 영향 분석
    """
    __tablename__ = "mood_check_ins"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    context_id = Column(Integer, ForeignKey("learning_contexts.id"), nullable=True, index=True)
    
    # 체크인 타이밍
    check_in_type = Column(String(20), nullable=False)  # "before_learning", "after_learning", "during_break"
    
    # 감정 상태
    mood = Column(String(20), nullable=False)  # "great", "good", "okay", "struggling", "frustrated", "exhausted"
    mood_emoji = Column(String(10), nullable=True)  # "😊", "😐", "😔", "😫"
    energy_level = Column(Integer, nullable=False)  # 1-10
    stress_level = Column(Integer, nullable=False)  # 1-10 (1: 편안함, 10: 매우 스트레스)
    
    # 감정에 대한 설명 (선택적)
    feeling_description = Column(Text, nullable=True)
    what_went_well = Column(Text, nullable=True)  # 잘된 점
    what_was_hard = Column(Text, nullable=True)  # 어려웠던 점
    
    # 신체 상태
    is_tired = Column(Boolean, default=False)
    is_hungry = Column(Boolean, default=False)
    is_distracted = Column(Boolean, default=False)
    
    # 타임스탬프
    checked_in_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    
    # 관계 설정
    user = relationship("User")
    
    # 인덱스
    __table_args__ = (
        Index('idx_mood_checkin_user_time', 'user_id', 'checked_in_at'),
        Index('idx_mood_checkin_type', 'check_in_type'),
        Index('idx_mood_checkin_mood', 'mood'),
    )


class EncouragingMessage(Base):
    """
    격려 메시지 시스템
    
    학습자의 상태에 따라 개인화된 격려 메시지 제공
    """
    __tablename__ = "encouraging_messages"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # 메시지 트리거
    trigger_type = Column(String(50), nullable=False, index=True)
    # "low_confidence", "consecutive_learning", "after_struggle", 
    # "first_success", "comeback", "milestone_reached"
    
    # 메시지 내용
    message = Column(Text, nullable=False)
    message_tone = Column(String(20), nullable=False)  # "gentle", "motivational", "celebratory", "empathetic"
    
    # 메시지 타입
    is_ai_generated = Column(Boolean, default=False)  # AI가 생성한 메시지인가
    is_personalized = Column(Boolean, default=True)  # 개인화된 메시지인가
    
    # 사용자 반응
    was_helpful = Column(Boolean, nullable=True)  # 도움이 되었는가
    user_feedback = Column(Text, nullable=True)
    
    # 컨텍스트
    context_data = Column(JSON, nullable=True)  # 메시지 생성 시 사용된 컨텍스트
    
    # 타임스탬프
    sent_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    read_at = Column(DateTime, nullable=True)
    
    # 관계 설정
    user = relationship("User")
    
    # 인덱스
    __table_args__ = (
        Index('idx_encouraging_message_user_sent', 'user_id', 'sent_at'),
        Index('idx_encouraging_message_trigger', 'trigger_type'),
        Index('idx_encouraging_message_helpful', 'was_helpful'),
    )