"""add_quote_table

Revision ID: 0a6771666795
Revises: e51c3f1b5e7b
Create Date: 2025-11-12 16:43:04.111528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6771666795'
down_revision: Union[str, None] = 'e51c3f1b5e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quote_active_order', 'quotes', ['is_active', 'order_number'], unique=False)
    op.create_index('idx_quote_category_active', 'quotes', ['category', 'is_active'], unique=False)
    op.create_index(op.f('ix_quotes_category'), 'quotes', ['category'], unique=False)
    op.create_index(op.f('ix_quotes_id'), 'quotes', ['id'], unique=False)
    op.create_index(op.f('ix_quotes_is_active'), 'quotes', ['is_active'], unique=False)
    op.create_index(op.f('ix_quotes_order_number'), 'quotes', ['order_number'], unique=True)
    op.create_table('dynamic_subject_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color_code', sa.String(length=10), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_subject_categories_id'), 'dynamic_subject_categories', ['id'], unique=False)
    op.create_index(op.f('ix_dynamic_subject_categories_key'), 'dynamic_subject_categories', ['key'], unique=True)
    op.create_table('dynamic_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('estimated_duration', sa.String(length=50), nullable=True),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('color_code', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('total_problems', sa.Integer(), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('average_completion_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['dynamic_subject_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_subjects_id'), 'dynamic_subjects', ['id'], unique=False)
    op.create_index(op.f('ix_dynamic_subjects_key'), 'dynamic_subjects', ['key'], unique=True)
    op.create_table('dynamic_subject_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_subject_id', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prerequisite_subject_id'], ['dynamic_subjects.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['dynamic_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_subject_prerequisites_id'), 'dynamic_subject_prerequisites', ['id'], unique=False)
    op.create_table('dynamic_subject_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('topic_key', sa.String(length=100), nullable=False),
    sa.Column('topic_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('parent_topic_id', sa.Integer(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('estimated_duration', sa.String(length=50), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('problem_count', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_topic_id'], ['dynamic_subject_topics.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['dynamic_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_subject_topics_id'), 'dynamic_subject_topics', ['id'], unique=False)
    op.create_index(op.f('ix_dynamic_subject_topics_topic_key'), 'dynamic_subject_topics', ['topic_key'], unique=False)
    op.drop_constraint('payments_order_id_key', 'payments', type_='unique')
    op.drop_constraint('payments_payment_key_key', 'payments', type_='unique')
    op.drop_index('ix_payments_order_id', table_name='payments')
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.drop_index('ix_payments_payment_key', table_name='payments')
    op.create_index(op.f('ix_payments_payment_key'), 'payments', ['payment_key'], unique=True)
    op.create_index('idx_payment_created_at', 'payments', ['created_at'], unique=False)
    op.drop_constraint('quiz_sessions_user_id_fkey', 'quiz_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint('subscriptions_user_id_key', 'subscriptions', type_='unique')
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_unique_constraint('subscriptions_user_id_key', 'subscriptions', ['user_id'])
    op.drop_constraint(None, 'quiz_sessions', type_='foreignkey')
    op.create_foreign_key('quiz_sessions_user_id_fkey', 'quiz_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_payment_created_at', table_name='payments')
    op.drop_index(op.f('ix_payments_payment_key'), table_name='payments')
    op.create_index('ix_payments_payment_key', 'payments', ['payment_key'], unique=False)
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.create_index('ix_payments_order_id', 'payments', ['order_id'], unique=False)
    op.create_unique_constraint('payments_payment_key_key', 'payments', ['payment_key'])
    op.create_unique_constraint('payments_order_id_key', 'payments', ['order_id'])
    op.drop_index(op.f('ix_dynamic_subject_topics_topic_key'), table_name='dynamic_subject_topics')
    op.drop_index(op.f('ix_dynamic_subject_topics_id'), table_name='dynamic_subject_topics')
    op.drop_table('dynamic_subject_topics')
    op.drop_index(op.f('ix_dynamic_subject_prerequisites_id'), table_name='dynamic_subject_prerequisites')
    op.drop_table('dynamic_subject_prerequisites')
    op.drop_index(op.f('ix_dynamic_subjects_key'), table_name='dynamic_subjects')
    op.drop_index(op.f('ix_dynamic_subjects_id'), table_name='dynamic_subjects')
    op.drop_table('dynamic_subjects')
    op.drop_index(op.f('ix_dynamic_subject_categories_key'), table_name='dynamic_subject_categories')
    op.drop_index(op.f('ix_dynamic_subject_categories_id'), table_name='dynamic_subject_categories')
    op.drop_table('dynamic_subject_categories')
    op.drop_index(op.f('ix_quotes_order_number'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_is_active'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_category'), table_name='quotes')
    op.drop_index('idx_quote_category_active', table_name='quotes')
    op.drop_index('idx_quote_active_order', table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
