"""add_hierarchical_subject_structure

Revision ID: 3b295f62ef44
Revises: bff0900ec6b9
Create Date: 2025-09-04 17:37:02.000223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b295f62ef44'
down_revision: Union[str, None] = 'bff0900ec6b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_hierarchy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('estimated_duration', sa.String(length=50), nullable=True),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('color_code', sa.String(length=10), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('total_problems', sa.Integer(), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('average_completion_rate', sa.Float(), nullable=True),
    sa.Column('prerequisites', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['subject_hierarchy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subject_hierarchy_active', 'subject_hierarchy', ['is_active'], unique=False)
    op.create_index('idx_subject_hierarchy_level', 'subject_hierarchy', ['level'], unique=False)
    op.create_index('idx_subject_hierarchy_parent_id', 'subject_hierarchy', ['parent_id'], unique=False)
    op.create_index('idx_subject_hierarchy_path', 'subject_hierarchy', ['path'], unique=False)
    op.create_index(op.f('ix_subject_hierarchy_id'), 'subject_hierarchy', ['id'], unique=False)
    op.create_index(op.f('ix_subject_hierarchy_key'), 'subject_hierarchy', ['key'], unique=True)
    op.create_index(op.f('ix_subject_hierarchy_level'), 'subject_hierarchy', ['level'], unique=False)
    op.create_index(op.f('ix_subject_hierarchy_parent_id'), 'subject_hierarchy', ['parent_id'], unique=False)
    op.create_index(op.f('ix_subject_hierarchy_path'), 'subject_hierarchy', ['path'], unique=True)
    op.add_column('questions', sa.Column('subject_path', sa.String(length=500), nullable=True))
    op.create_index('idx_question_subject_path', 'questions', ['subject_path'], unique=False)
    op.create_index(op.f('ix_questions_subject_path'), 'questions', ['subject_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_subject_path'), table_name='questions')
    op.drop_index('idx_question_subject_path', table_name='questions')
    op.drop_column('questions', 'subject_path')
    op.drop_index(op.f('ix_subject_hierarchy_path'), table_name='subject_hierarchy')
    op.drop_index(op.f('ix_subject_hierarchy_parent_id'), table_name='subject_hierarchy')
    op.drop_index(op.f('ix_subject_hierarchy_level'), table_name='subject_hierarchy')
    op.drop_index(op.f('ix_subject_hierarchy_key'), table_name='subject_hierarchy')
    op.drop_index(op.f('ix_subject_hierarchy_id'), table_name='subject_hierarchy')
    op.drop_index('idx_subject_hierarchy_path', table_name='subject_hierarchy')
    op.drop_index('idx_subject_hierarchy_parent_id', table_name='subject_hierarchy')
    op.drop_index('idx_subject_hierarchy_level', table_name='subject_hierarchy')
    op.drop_index('idx_subject_hierarchy_active', table_name='subject_hierarchy')
    op.drop_table('subject_hierarchy')
    # ### end Alembic commands ###
