"""add_user_note_table

Revision ID: 5a8e32d7c0fb
Revises: 0a6771666795
Create Date: 2025-11-14 21:10:10.271712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8e32d7c0fb'
down_revision: Union[str, None] = '0a6771666795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('is_important', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['learning_modules.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['learning_tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_note_important', 'user_notes', ['is_important'], unique=False)
    op.create_index('idx_user_note_module', 'user_notes', ['module_id'], unique=False)
    op.create_index('idx_user_note_track', 'user_notes', ['track_id'], unique=False)
    op.create_index('idx_user_note_user_created', 'user_notes', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_notes_created_at'), 'user_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_notes_id'), 'user_notes', ['id'], unique=False)
    op.create_index(op.f('ix_user_notes_module_id'), 'user_notes', ['module_id'], unique=False)
    op.create_index(op.f('ix_user_notes_track_id'), 'user_notes', ['track_id'], unique=False)
    op.create_index(op.f('ix_user_notes_user_id'), 'user_notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_notes_user_id'), table_name='user_notes')
    op.drop_index(op.f('ix_user_notes_track_id'), table_name='user_notes')
    op.drop_index(op.f('ix_user_notes_module_id'), table_name='user_notes')
    op.drop_index(op.f('ix_user_notes_id'), table_name='user_notes')
    op.drop_index(op.f('ix_user_notes_created_at'), table_name='user_notes')
    op.drop_index('idx_user_note_user_created', table_name='user_notes')
    op.drop_index('idx_user_note_track', table_name='user_notes')
    op.drop_index('idx_user_note_module', table_name='user_notes')
    op.drop_index('idx_user_note_important', table_name='user_notes')
    op.drop_table('user_notes')
    # ### end Alembic commands ###
