"""add indexes for dashboard

Revision ID: 963a85d8bbe8
Revises: 2c47454cbb47
Create Date: 2025-08-08 15:33:39.389227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963a85d8bbe8'
down_revision: Union[str, None] = '2c47454cbb47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_submission_items_topic'), 'submission_items', ['topic'], unique=False)
    op.create_index(op.f('ix_submissions_submitted_at'), 'submissions', ['submitted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_submitted_at'), table_name='submissions')
    op.drop_index(op.f('ix_submission_items_topic'), table_name='submission_items')
    # ### end Alembic commands ###
