"""add_emotional_support_models

Revision ID: b2ffb027ab6d
Revises: 5a8e32d7c0fb
Create Date: 2025-11-15 00:55:31.197229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ffb027ab6d'
down_revision: Union[str, None] = '5a8e32d7c0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encouraging_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_tone', sa.String(length=20), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('is_personalized', sa.Boolean(), nullable=True),
    sa.Column('was_helpful', sa.Boolean(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_encouraging_message_helpful', 'encouraging_messages', ['was_helpful'], unique=False)
    op.create_index('idx_encouraging_message_trigger', 'encouraging_messages', ['trigger_type'], unique=False)
    op.create_index('idx_encouraging_message_user_sent', 'encouraging_messages', ['user_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_encouraging_messages_id'), 'encouraging_messages', ['id'], unique=False)
    op.create_index(op.f('ix_encouraging_messages_sent_at'), 'encouraging_messages', ['sent_at'], unique=False)
    op.create_index(op.f('ix_encouraging_messages_trigger_type'), 'encouraging_messages', ['trigger_type'], unique=False)
    op.create_index(op.f('ix_encouraging_messages_user_id'), 'encouraging_messages', ['user_id'], unique=False)
    op.create_table('learning_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('mood', sa.String(length=20), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('confidence_level', sa.Integer(), nullable=True),
    sa.Column('study_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_first_session_today', sa.Boolean(), nullable=True),
    sa.Column('interruptions_count', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.String(length=20), nullable=True),
    sa.Column('is_consecutive_day', sa.Boolean(), nullable=True),
    sa.Column('consecutive_days_count', sa.Integer(), nullable=True),
    sa.Column('daily_goal', sa.String(length=200), nullable=True),
    sa.Column('motivation_level', sa.Integer(), nullable=True),
    sa.Column('why_learning_today', sa.Text(), nullable=True),
    sa.Column('current_struggle', sa.Text(), nullable=True),
    sa.Column('needs_encouragement', sa.Boolean(), nullable=True),
    sa.Column('preferred_support_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['learning_modules.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['learning_tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_learning_context_mood', 'learning_contexts', ['mood'], unique=False)
    op.create_index('idx_learning_context_session', 'learning_contexts', ['session_id'], unique=False)
    op.create_index('idx_learning_context_user_created', 'learning_contexts', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_learning_contexts_created_at'), 'learning_contexts', ['created_at'], unique=False)
    op.create_index(op.f('ix_learning_contexts_id'), 'learning_contexts', ['id'], unique=False)
    op.create_index(op.f('ix_learning_contexts_session_id'), 'learning_contexts', ['session_id'], unique=False)
    op.create_index(op.f('ix_learning_contexts_user_id'), 'learning_contexts', ['user_id'], unique=False)
    op.create_table('mood_check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('check_in_type', sa.String(length=20), nullable=False),
    sa.Column('mood', sa.String(length=20), nullable=False),
    sa.Column('mood_emoji', sa.String(length=10), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=False),
    sa.Column('stress_level', sa.Integer(), nullable=False),
    sa.Column('feeling_description', sa.Text(), nullable=True),
    sa.Column('what_went_well', sa.Text(), nullable=True),
    sa.Column('what_was_hard', sa.Text(), nullable=True),
    sa.Column('is_tired', sa.Boolean(), nullable=True),
    sa.Column('is_hungry', sa.Boolean(), nullable=True),
    sa.Column('is_distracted', sa.Boolean(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['learning_contexts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mood_checkin_mood', 'mood_check_ins', ['mood'], unique=False)
    op.create_index('idx_mood_checkin_type', 'mood_check_ins', ['check_in_type'], unique=False)
    op.create_index('idx_mood_checkin_user_time', 'mood_check_ins', ['user_id', 'checked_in_at'], unique=False)
    op.create_index(op.f('ix_mood_check_ins_checked_in_at'), 'mood_check_ins', ['checked_in_at'], unique=False)
    op.create_index(op.f('ix_mood_check_ins_context_id'), 'mood_check_ins', ['context_id'], unique=False)
    op.create_index(op.f('ix_mood_check_ins_id'), 'mood_check_ins', ['id'], unique=False)
    op.create_index(op.f('ix_mood_check_ins_user_id'), 'mood_check_ins', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mood_check_ins_user_id'), table_name='mood_check_ins')
    op.drop_index(op.f('ix_mood_check_ins_id'), table_name='mood_check_ins')
    op.drop_index(op.f('ix_mood_check_ins_context_id'), table_name='mood_check_ins')
    op.drop_index(op.f('ix_mood_check_ins_checked_in_at'), table_name='mood_check_ins')
    op.drop_index('idx_mood_checkin_user_time', table_name='mood_check_ins')
    op.drop_index('idx_mood_checkin_type', table_name='mood_check_ins')
    op.drop_index('idx_mood_checkin_mood', table_name='mood_check_ins')
    op.drop_table('mood_check_ins')
    op.drop_index(op.f('ix_learning_contexts_user_id'), table_name='learning_contexts')
    op.drop_index(op.f('ix_learning_contexts_session_id'), table_name='learning_contexts')
    op.drop_index(op.f('ix_learning_contexts_id'), table_name='learning_contexts')
    op.drop_index(op.f('ix_learning_contexts_created_at'), table_name='learning_contexts')
    op.drop_index('idx_learning_context_user_created', table_name='learning_contexts')
    op.drop_index('idx_learning_context_session', table_name='learning_contexts')
    op.drop_index('idx_learning_context_mood', table_name='learning_contexts')
    op.drop_table('learning_contexts')
    op.drop_index(op.f('ix_encouraging_messages_user_id'), table_name='encouraging_messages')
    op.drop_index(op.f('ix_encouraging_messages_trigger_type'), table_name='encouraging_messages')
    op.drop_index(op.f('ix_encouraging_messages_sent_at'), table_name='encouraging_messages')
    op.drop_index(op.f('ix_encouraging_messages_id'), table_name='encouraging_messages')
    op.drop_index('idx_encouraging_message_user_sent', table_name='encouraging_messages')
    op.drop_index('idx_encouraging_message_trigger', table_name='encouraging_messages')
    op.drop_index('idx_encouraging_message_helpful', table_name='encouraging_messages')
    op.drop_table('encouraging_messages')
    # ### end Alembic commands ###
