"""Add taxonomy_level, hint, explanation to Question model

Revision ID: bff0900ec6b9
Revises: 18e7e9cf2a9c
Create Date: 2025-09-03 17:10:25.614740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff0900ec6b9'
down_revision: Union[str, None] = '18e7e9cf2a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ai_content_generation_logs_id'), 'ai_content_generation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_generated_curricula_id'), 'ai_generated_curricula', ['id'], unique=False)
    op.drop_index('ix_ai_teaching_sessions_status', table_name='ai_teaching_sessions')
    op.create_index(op.f('ix_ai_teaching_sessions_id'), 'ai_teaching_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_teaching_sessions_session_status'), 'ai_teaching_sessions', ['session_status'], unique=False)
    op.add_column('questions', sa.Column('taxonomy_level', sa.String(length=50), nullable=True))
    op.add_column('questions', sa.Column('hint', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'explanation')
    op.drop_column('questions', 'hint')
    op.drop_column('questions', 'taxonomy_level')
    op.drop_index(op.f('ix_ai_teaching_sessions_session_status'), table_name='ai_teaching_sessions')
    op.drop_index(op.f('ix_ai_teaching_sessions_id'), table_name='ai_teaching_sessions')
    op.create_index('ix_ai_teaching_sessions_status', 'ai_teaching_sessions', ['session_status'], unique=False)
    op.drop_index(op.f('ix_ai_generated_curricula_id'), table_name='ai_generated_curricula')
    op.drop_index(op.f('ix_ai_content_generation_logs_id'), table_name='ai_content_generation_logs')
    # ### end Alembic commands ###
